// Static vibes configuration — the song analysis attributes used by the AI profile generator.
// Edit this file to add, remove, or modify vibes. Set archived: true to exclude a vibe from generation.
// The slug is the stable identifier (category.name format) — never change it after creation. Name is a display label and can be freely edited.

export interface Vibe {
  slug: string;
  name: string;
  archived: boolean;
  category: string;
  description: string;
  instruction: string;
  example: string;
}

export const vibes: readonly Vibe[] = [
  // ---------------------------------------------------------------------------
  // GENRE
  // ---------------------------------------------------------------------------
  { slug: "genre.genre", name: "Genre", archived: false, category: "genre", description: "Detailed genres from primary to least, ordered by greatest influence", instruction: "Start with a general genre, but then list genre specifics that makes this song different within it's own genre", example: "Bubblegum Pop, Trap Metal, East Coast Boom-Bap, Street Rap" },
  { slug: "genre.era-influence", name: "Era Influence", archived: false, category: "genre", description: "Decade or period the sound draws from", instruction: "What era of music is this being influenced by? Start with the year, but list the specific style from that time period that influenced", example: "late 80s synth-pop, 2010s SoundCloud rap, 70s Philly soul" },
  { slug: "genre.cultural-origin", name: "Cultural Origin", archived: false, category: "genre", description: "Regional or cultural roots and specific stylistic niche", instruction: "What culture and the style within the culture is this song being influenced by?", example: "Korean idol pop, Lagos Afrobeat, European Italo-Disco, Caribbean Dancehall, Polska Polka" },

  // ---------------------------------------------------------------------------
  // STRUCTURE
  // ---------------------------------------------------------------------------
  { slug: "structure.song-structure", name: "Song Structure", archived: false, category: "structure", description: "Exact section-by-section flow of the song", instruction: "Identify the song structure. Is there an intro? Are there verses? Is there a chorus? List the entire structural flow.", example: "Intro -> Verse 1 -> Pre-Chorus -> Chorus -> Verse 2 -> Pre-Chorus -> Chorus -> Bridge -> Final Chorus -> Outro" },
  { slug: "structure.verse-style", name: "Verse Style", archived: false, category: "structure", description: "Verse characteristics", instruction: "Examine the verses (if any). Identify the size of the verse, vocals (gender, vocal arrangement, ensemble size), weight (emotional intensity, energy, etc), repetition (does it repeat words, phrases or the entire thing, and how often)", example: "long, structured as 2 parallel 4-line halves. Female, solo arrangement. Lighthearted, quirky and upbeat romantic energy." },
  { slug: "structure.chorus-style", name: "Chorus Style", archived: false, category: "structure", description: "Chorus characteristics", instruction: "Examine the chorus (if any). Identify the size of the chorus, vocals (gender, vocal arrangement, ensemble size), weight (emotional intensity, energy, etc), repetition (does it repeat words, phrases or the entire thing, and how often)", example: "short 4-bar. Upbeat, high energy and catchy. Male, solo arrangement. Repeats the beginning phrase twice." },
  { slug: "structure.intro-style", name: "Intro Style", archived: false, category: "structure", description: "Intro unique characteristics", instruction: "Examine the intro of the song, even if it doesn't have intro lyrics. Note the duration, instrumentation used. Does the music ease-in, or does it begin right away.", example: "15-second slow fade-in. Ambient synth pads. 8-bar cold open of heavy guitar. 10-second acapella before sudden bass drop. Immediately starts with the verse." },
  { slug: "structure.outro-style", name: "Outro Style", archived: false, category: "structure", description: "How the song closes", instruction: "Examine the ending of the song. Determine if it ends on a definitive note, fades out, breaks down into specific elements. Note vocals, musical instrument, energy.", example: "Abrupt heavy guitar stop. Low-energy solo piano decay. Crowd noise fade. High energy repeating chorus." },
  { slug: "structure.duration", name: "Duration", archived: false, category: "structure", description: "Total song length", instruction: "Identify the total running time of the audio provided. Note if it is a specific mix format based on length.", example: "3:42, 7:12 extended mix" },
  { slug: "structure.energy-arc", name: "Energy Arc", archived: false, category: "structure", description: "How dynamic energy rises and falls across the full timeline", instruction: "Map the intensity from start to finish. Identify the build, peak, drop, and resolution.", example: "low simmering verse builds into explosive chorus, drops to near-silence at bridge, erupts into double-time final chorus, steady escalation from start to finish with no release" },
  { slug: "structure.transitions", name: "Transitions", archived: false, category: "structure", description: "Type and feel of connections between sections", instruction: "Identify how the song moves between major sections. Note the techniques, fills, or effects used to bridge gaps.", example: "riser sweeps into each chorus, drum fill transitions, silence gaps between verse and chorus, reversed vocal crossfade, beat drops out leaving only bass before chorus hits" },
  { slug: "structure.section-contrast", name: "Section Contrast", archived: false, category: "structure", description: "How different sections feel from each other", instruction: "Compare distinct song parts. Highlight primary differences in instrumentation, vocal delivery, or energy.", example: "rapped verses vs melodic sung chorus, acoustic verse into full-band chorus, whispered bridge against screamed chorus, kids church choir chorus vs street-rap verses" },

  // ---------------------------------------------------------------------------
  // COMPOSITION
  // ---------------------------------------------------------------------------
  { slug: "composition.key", name: "Key", archived: false, category: "composition", description: "Musical key, scale, and mode", instruction: "Identify the primary tonal center of the song, including the root note and the specific scale or mode used.", example: "C minor natural, F# Dorian, E major pentatonic" },
  { slug: "composition.tempo", name: "Tempo", archived: false, category: "composition", description: "BPM, grid feel, and any fluctuation", instruction: "Determine the approximate beats per minute (BPM). Note if the tempo stays strict, fluctuates, or changes entirely during the song.", example: "92 BPM tight grid, 140 BPM half-time feel, starts 70 BPM accelerates to 120 by final chorus, loose human tempo drift" },
  { slug: "composition.time-signature", name: "Time Signature", archived: false, category: "composition", description: "Rhythmic meter", instruction: "Identify the number of beats per measure and the note value that gets the beat. Note any odd meters or shifts in time signature.", example: "4/4, 3/4 waltz, 6/8 compound, alternates 7/8 and 4/4" },
  { slug: "composition.chord-progression", name: "Chord Progression", archived: false, category: "composition", description: "Specific chord sequences per section", instruction: "Analyze the underlying harmonic movement. Detail the chord patterns used in distinct sections using Roman numeral analysis or general descriptions.", example: "verse: i-VI-III-VII, chorus: I-V-vi-IV; single chord drone throughout; jazz ii-V-I turnarounds with chromatic passing chords" },
  { slug: "composition.melody", name: "Melody", archived: false, category: "composition", description: "Core melodic hooks, contour, and motifs", instruction: "Describe the primary musical phrases sung or played. Focus on the shape of the melody, its catchiness, and how instruments interact with it.", example: "descending minor pentatonic hook with call-and-response between vocal and synth, one-note chant melody, soaring octave-leap chorus hook" },

  // ---------------------------------------------------------------------------
  // RHYTHM
  // ---------------------------------------------------------------------------
  { slug: "rhythm.rhythmic-feel", name: "Rhythmic Feel", archived: false, category: "rhythm", description: "How the beat physically sits and moves", instruction: "Describe the \"pocket\" or groove of the track. Is it rigid and quantized, or loose and swung?", example: "straight and mechanical, swung 16ths, heavy syncopation, lazy behind-the-beat drag, tight and punchy" },
  { slug: "rhythm.drum-pattern", name: "Drum Pattern", archived: false, category: "rhythm", description: "Drum style, pattern, and character", instruction: "Identify the primary drum loop or beat. Note the specific kit type and the rhythmic pattern played by the kick, snare, and hi-hats.", example: "trap hi-hats with rolling triplets, four-on-the-floor house kick, boom-bap breakbeat, live jazz brushes, no drums — percussion-free" },
  { slug: "rhythm.bass-groove", name: "Bass Groove", archived: false, category: "rhythm", description: "Bass rhythm, character, and role", instruction: "Analyze the low-end foundation. Describe the tone of the bass instrument and how it interacts rhythmically with the drums.", example: "808 sub-bass slides, fingerstyle Motown walking bass, distorted synth bass pulsing on downbeats, bass drops only on chorus" },
  { slug: "rhythm.percussion-elements", name: "Percussion Elements", archived: false, category: "rhythm", description: "Non-drum percussion adding texture", instruction: "Listen for auxiliary rhythmic instruments outside the main drum kit. Detail what they are and where they hit in the measure.", example: "shaker and finger snaps on 2 and 4, tabla and hand drums, cowbell driving the groove, none" },

  // ---------------------------------------------------------------------------
  // INSTRUMENTATION
  // ---------------------------------------------------------------------------
  { slug: "instrumentation.primary-instruments", name: "Primary Instruments", archived: false, category: "instrumentation", description: "Dominant instruments carrying the song", instruction: "Identify the main instruments that drive the melodic and harmonic foundation of the track.", example: "detuned honky-tonk piano, 808 kit; clean electric guitar arpeggios, analog Moog bass" },
  { slug: "instrumentation.secondary-instruments", name: "Secondary Instruments", archived: false, category: "instrumentation", description: "Supporting or textural instruments", instruction: "Identify background instruments that add depth, color, or texture but do not lead the song.", example: "ambient string pads, marimba accents; organ swells in chorus only; orchestral brass stabs" },
  { slug: "instrumentation.instrument-technique", name: "Instrument Technique", archived: false, category: "instrumentation", description: "Specific playing styles, unorthodox methods, and what makes them different", instruction: "Listen for unique ways the instruments are physically played. Describe any distinct articulations or unconventional techniques.", example: "palm-muted guitar with heavy pick scrapes, bowed electric bass, prepared piano with objects on strings, slap bass with thumb muting" },
  { slug: "instrumentation.instrument-effects", name: "Instrument Effects", archived: false, category: "instrumentation", description: "Effects processing on instruments", instruction: "Detail any obvious audio effects applied to the instruments to change their natural tone.", example: "heavy flanger on guitar, bit-crushed synth leads, reversed reverb piano swells, tremolo on Rhodes" },
  { slug: "instrumentation.arrangement-dynamics", name: "Arrangement Dynamics", archived: false, category: "instrumentation", description: "When and how instrumental elements enter, exit, and layer across the timeline", instruction: "Map how the instrumentation builds or strips away over time. Note specific sections where elements drop out or stack together.", example: "drums drop out in verse 2, strings enter at bridge, full band at final chorus; instruments added one by one each 8 bars; everything cuts except vocals for 2 beats before chorus drops" },

  // ---------------------------------------------------------------------------
  // VOCALS
  // ---------------------------------------------------------------------------
  { slug: "vocals.vocal-cast", name: "Vocal Cast", archived: false, category: "vocals", description: "Who sings what and where — maps out each distinct voice and their role across sections", instruction: "Identify all distinct vocalists on the track. Note their gender/tone and assign which sections of the song they perform.", example: "solo male rapper on verses, female soul singer on hook/chorus; single vocalist throughout; male lead on verses, male-female duet on chorus, children's choir on bridge; rapper A on verse 1, rapper B on verse 2, singer on all hooks" },
  { slug: "vocals.vocal-timbre", name: "Vocal Timbre", archived: false, category: "vocals", description: "Physical texture and tonal quality of each voice in the cast", instruction: "Describe the unique sonic character of the singer's voice. Use physical and textural adjectives.", example: "rapper: warm and husky; hook singer: raspy soul tone with raw grit; bright and nasal throughout; deep resonant baritone" },
  { slug: "vocals.vocal-range", name: "Vocal Range", archived: false, category: "vocals", description: "Pitch range and register used", instruction: "Identify how high or low the vocalist is singing, and note what vocal register (chest, head, falsetto) they are utilizing.", example: "alto chest voice, tenor with falsetto in chorus, spans 3 octaves from low growl to whistle register" },
  { slug: "vocals.vocal-style", name: "Vocal Style", archived: false, category: "vocals", description: "Delivery technique", instruction: "Describe how the vocalist is delivering the performance. Is it sung, rapped, spoken, or something else?", example: "belting, whisper-singing, rapid-fire rap, spoken-word, yodeling between registers, melodic sing-rap" },
  { slug: "vocals.vocal-sync", name: "Vocal Sync", archived: false, category: "vocals", description: "How the voice rides and locks with the beat", instruction: "Analyze the rhythmic timing of the vocals relative to the instrumental track.", example: "tight rhythmic phrasing locked to grid, lazy dragging behind the beat, staccato machine-gun syllables, free-flowing over bar lines, syncopated pushes ahead of the beat" },
  { slug: "vocals.vocal-emotion", name: "Vocal Emotion", archived: false, category: "vocals", description: "Emotional intensity and character of delivery", instruction: "Determine the feeling or attitude the vocalist is projecting through their performance.", example: "vulnerable and pleading, aggressive and confrontational, detached and deadpan, manic and unhinged, joyful and carefree" },
  { slug: "vocals.vocal-accent", name: "Vocal Accent", archived: false, category: "vocals", description: "Cultural, regional, or dialectal inflection", instruction: "Listen for any specific regional accents or cultural dialects present in the pronunciation of the words.", example: "Southern US drawl, heavy New York street inflection, Caribbean Patois flavor, London roadman cadence, AAVE with Trinidadian accent, neutral/no notable accent" },
  { slug: "vocals.vocal-effects", name: "Vocal Effects", archived: false, category: "vocals", description: "Processing and effects on the voice", instruction: "Detail any obvious studio effects applied to the lead vocals.", example: "heavy autotune, dry with no reverb, vocoder harmonies, telephone EQ filter on verse, heavy slapback delay" },
  { slug: "vocals.backing-vocals", name: "Backing Vocals", archived: false, category: "vocals", description: "Backing vocal style, placement, role, and where they appear", instruction: "Identify any secondary vocals supporting the lead. Describe what they are doing (harmonies, ad-libs) and where they occur.", example: "lush choir harmonies on chorus only, call-and-response ad-libs throughout, gang vocal shouts on hook, layered self-harmonies stacked 6 deep, kid's choir on bridge, none" },

  // ---------------------------------------------------------------------------
  // LYRICS
  // ---------------------------------------------------------------------------
  { slug: "lyrics.language", name: "Language", archived: false, category: "lyrics", description: "Language or languages sung in", instruction: "Identify the primary language of the lyrics, noting if multiple languages are used.", example: "English, Korean with English chorus, Spanish and English code-switching" },
  { slug: "lyrics.lyrical-subject", name: "Lyrical Subject", archived: false, category: "lyrics", description: "Topic category of what the song is about", instruction: "Determine the broad thematic category of the lyrics. What is the overarching topic?", example: "relationships, street life and survival, politics and world order, money and materialism, self-empowerment, partying and nightlife, spirituality and faith, mental health, nostalgia and memory" },
  { slug: "lyrics.lyrical-message", name: "Lyrical Message", archived: false, category: "lyrics", description: "The core message or intent — what the author is trying to tell the listener", instruction: "Analyze the deeper meaning of the lyrics. What specific point, story, or moral is the artist conveying?", example: "cautionary tale about greed consuming everything, celebrating overcoming struggle, processing unresolved grief, pure wordplay and flexing with no deeper message, cry for help disguised as a party song, warning to enemies" },
  { slug: "lyrics.lyrical-tone", name: "Lyrical Tone", archived: false, category: "lyrics", description: "Emotional stance and attitude of the words themselves", instruction: "Evaluate the attitude or mood of the written lyrics, separate from the musical delivery.", example: "vengeful payback, carefree joy, bitter resentment, hopeful yearning, feeling misunderstood, cocky braggadocio, grateful and reflective, defeated and resigned" },
  { slug: "lyrics.narrative-style", name: "Narrative Style", archived: false, category: "lyrics", description: "The type and mode of lyrical content", instruction: "Describe how the lyrics are structured conceptually. Is it a literal story, abstract poetry, or conversational?", example: "storytelling with beginning, middle, end; emotional venting and confessional; boasting and flexing; repetitive wordplay and hooks; spoken-word poetry; abstract imagery with no literal narrative; conversational as if talking to someone; anthem — rallying cry meant to be chanted" },
  { slug: "lyrics.narrative-pov", name: "Narrative POV", archived: false, category: "lyrics", description: "Point of view and how it shifts across the song", instruction: "Identify the perspective from which the lyrics are delivered (1st, 2nd, or 3rd person) and note if it changes between sections.", example: "first-person throughout, third-person storytelling, second-person — speaking directly to 'you', first-person verses shift to third-person chorus, alternating perspectives between verse 1 and verse 2, omniscient narrator in verses, first-person confession in bridge" },
  { slug: "lyrics.rhyme-scheme", name: "Rhyme Scheme", archived: false, category: "lyrics", description: "Rhyming patterns per section with internal rhymes noted", instruction: "Analyze the structural pattern of rhymes at the end of lines, as well as any notable rhyming within the lines themselves.", example: "AABB couplets in verse, ABAB in chorus; dense multisyllabic internal rhymes; free verse no rhyme; chorus is a single repeated phrase" },
  { slug: "lyrics.poetic-devices", name: "Poetic Devices", archived: false, category: "lyrics", description: "Literary and rhetorical techniques used", instruction: "Identify any advanced lyrical techniques such as metaphors, similes, alliteration, or irony.", example: "heavy metaphor and simile, alliteration in hooks, anaphora — each verse starts with 'I remember', ironic contrast between upbeat sound and dark lyrics, none — straightforward and literal" },
  { slug: "lyrics.lyrical-flow", name: "Lyrical Flow", archived: false, category: "lyrics", description: "Cadence, meter, and rhythmic phrasing of words", instruction: "Describe the rhythm and pacing of how the words are delivered.", example: "rapid-fire 16th note syllables, slow deliberate phrasing with long pauses, sing-song nursery rhyme cadence, conversational and loose, triplet flow" },
  { slug: "lyrics.lyrical-density", name: "Lyrical Density", archived: false, category: "lyrics", description: "How packed or sparse the words are per section", instruction: "Evaluate the word count relative to the music. Are the sections crammed with lyrics or are they sparse with room to breathe?", example: "wall-to-wall words no breathing room, minimal 4 lines per verse, chorus is one repeated word, dense verses but wide-open sparse chorus" },

  // ---------------------------------------------------------------------------
  // PRODUCTION
  // ---------------------------------------------------------------------------
  { slug: "production.production-style", name: "Production Style", archived: false, category: "production", description: "Overall sonic approach and era", instruction: "Describe the overarching aesthetic of the recording and production. Does it sound modern, retro, clean, or gritty?", example: "polished maximalist pop, lo-fi bedroom with tape hiss, raw live recording, hyper-processed futuristic, stripped acoustic" },
  { slug: "production.mix-character", name: "Mix Character", archived: false, category: "production", description: "Sonic quality, vocal placement, and depth", instruction: "Analyze the frequency balance and spatial depth of the mix. Note where the vocals sit relative to the instrumental.", example: "vocal up front and dry, intimate feel; vocals buried in reverb wall, stadium sound; bass-heavy low-end dominant; bright and crispy highs" },
  { slug: "production.stereo-field", name: "Stereo Field", archived: false, category: "production", description: "Panning and spatial layout", instruction: "Listen to the left and right channels. Describe how wide the mix is and if specific elements are panned aggressively.", example: "guitars hard-panned left and right, drums dead center; wide immersive stereo; narrow mono-focused; elements ping-pong between channels" },
  { slug: "production.sound-design", name: "Sound Design", archived: false, category: "production", description: "Non-musical sounds, foley, and sonic textures", instruction: "Identify any environmental sounds, noises, or purely textural audio elements that aren't traditional instruments.", example: "vinyl crackle throughout, rain and thunder in intro, glitch artifacts and digital noise, field recording of city traffic under verse, none" },
  { slug: "production.sampling", name: "Sampling", archived: false, category: "production", description: "Notable samples and their treatment", instruction: "Determine if the track utilizes audio recorded from other songs or media, and describe how it was manipulated.", example: "chops a 70s soul vocal into the hook, pitch-shifted classical piano sample, breakbeat from classic funk record, none" },

  // ---------------------------------------------------------------------------
  // MOOD
  // ---------------------------------------------------------------------------
  { slug: "mood.overall-mood", name: "Overall Mood", archived: false, category: "mood", description: "Overarching emotional atmosphere in precise terms", instruction: "Summarize the primary emotion or feeling the track evokes in the listener.", example: "euphoric, creeping dread, simmering tension, bittersweet nostalgia, manic and frantic, anthemic and triumphant" },
  { slug: "mood.danceability", name: "Danceability", archived: false, category: "mood", description: "Type and intensity of movement it drives", instruction: "Evaluate how the rhythm and groove compel physical movement. What kind of dancing does it suit?", example: "club-ready four-on-the-floor pulse, head-nod groove, mosh pit energy, slow sway, sit and listen — not danceable" },

  // ---------------------------------------------------------------------------
  // ENERGY
  // ---------------------------------------------------------------------------
  { slug: "energy.pace", name: "Pace", archived: false, category: "energy", description: "Perceived speed and momentum of the track regardless of BPM", instruction: "Describe the subjective feeling of speed. Does the song feel fast and urgent or slow and sluggish, regardless of the actual tempo?", example: "breakneck and relentless, slow heavy crawl, gradually accelerating, stop-start lurching, half-time crawl despite high BPM" },
  { slug: "energy.intensity", name: "Intensity", archived: false, category: "energy", description: "How hard the track hits and how much force it carries", instruction: "Evaluate the sheer sonic force and weight of the song.", example: "explosive and overwhelming, gentle and delicate, simmering just below boiling, crushing and suffocating, featherlight" },
  { slug: "energy.tension", name: "Tension", archived: false, category: "energy", description: "Suspense, anxiety, and release quality", instruction: "Analyze how the song builds anticipation. Does it resolve that anticipation, or leave the listener hanging?", example: "anxious and taut, relaxed and loose, building with no release, constant tension-release cycle, unresolved and unsettling" },
  { slug: "energy.energy-texture", name: "Energy Texture", archived: false, category: "energy", description: "Physical quality and shape of the energy", instruction: "Use tactile adjectives to describe how the energy of the song feels.", example: "bouncy and springy, heavy and grinding, floaty and weightless, jagged and angular, smooth and flowing, sticky and syrupy" },
  { slug: "energy.atmosphere", name: "Atmosphere", archived: false, category: "energy", description: "Immersive or altered-state quality of the sonic space", instruction: "Describe the ambient \"space\" the song creates. Does it transport the listener to a specific psychological or environmental space?", example: "surreal and dreamlike, hypnotic and trance-inducing, psychedelic and disorienting, claustrophobic and suffocating, vast and cinematic, underwater and submerged" },

  // ---------------------------------------------------------------------------
  // SIGNATURE
  // ---------------------------------------------------------------------------
  { slug: "signature.signature-quirks", name: "Signature Quirks", archived: false, category: "signature", description: "One-of-a-kind imperfections, oddities, and distinguishing details that make this song unlike any other", instruction: "Listen very closely for tiny, easily missed details, mistakes, or unique studio choices that give the track distinct character.", example: "snare slightly off-grid giving a human lurch, cough left in at 2:14, guitar intentionally detuned, vocalist laughs mid-line in verse 2, record scratch used as melodic instrument" },
  { slug: "signature.signature-moments", name: "Signature Moments", archived: false, category: "signature", description: "The defining, most memorable musical events or passages that everyone remembers", instruction: "Identify the \"wow\" moments of the song. What is the most iconic, standout section that defines the entire track?", example: "3-minute vocoder solo as outro, beat completely switches genre at bridge, acapella breakdown at 2:30, orchestra swells as drums cut for 4 bars before final chorus, guitar solo over key change, entire crowd chant section" },
];

/** Returns only non-archived vibes */
export function getActiveVibes(): Vibe[] {
  return vibes.filter((v) => !v.archived);
}

/** Total count of all vibes (including archived) */
export function getVibeCount(): number {
  return vibes.length;
}
